volumes:
  jellyfin-cache:

services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/jellyfin/config:/config
      - jellyfin-cache:/cache
      - ${DATA_DIR}/${MEDIA_FOLDER}:/data/media
    ports:
      - "8096:8096"


  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
    volumes:
      - ${CONFIG_DIR}/jellyseerr/config:/app/config
    ports:
      - "5055:5055"
    depends_on:
      - jellyfin


  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/bazarr/config:/config
      - ${DATA_DIR}/${MEDIA_FOLDER}:/media
    ports:
      - "6767:6767"


  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/radarr/config:/config
      - ${DATA_DIR}:/data
    ports:
      - "7878:7878"
    depends_on:
      - vpn-qbittorrent


  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr/config:/config
      - ${DATA_DIR}:/data
    ports:
      - "8989:8989"
    depends_on:
      - vpn-qbittorrent


  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/prowlarr/config:/config
    ports:
      - "9696:9696"


  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    network_mode: "service:vpn-qbittorrent"
    volumes:
      - ${CONFIG_DIR}/qbittorrent/config:/config
      - ${DATA_DIR}/${TORRENTS_FOLDER}:/data/torrents
    depends_on:
      - vpn-qbittorrent

  vpn-qbittorrent:
    image: qmcgaw/gluetun:latest
    container_name: vpn-qbittorrent
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - VPN_USERNAME=${VPN_USERNAME}
      - VPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
    volumes:
      - ${CONFIG_DIR}/gluetun:/gluetun
    ports:
      - "8080:8080" # qBittorrent Web UI